(()=>{var e={};e.id=244,e.ids=[244],e.modules={399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},9348:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},412:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},5900:e=>{"use strict";e.exports=require("pg")},9026:(e,r,t)=>{"use strict";t.r(r),t.d(r,{patchFetch:()=>$,routeModule:()=>c,serverHooks:()=>m,workAsyncStorage:()=>p,workUnitAsyncStorage:()=>l});var s={};t.r(s),t.d(s,{POST:()=>u});var a=t(4810),n=t(8530),o=t(3872),i=t(8536);let d=new(t(5900)).Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:!1}});async function u(e){try{let{type:r,answer_number:t,comments:s,username:a,id:n,category:o,usernames:u,service:c,link:p,quantity:l,charge:m,refill:$,panel:f,name:g,rt:h}=await e.json(),v="";"Default"===r?v=`https://godofpanel.com/api/v2?key=7aed775ad8b88b50a1706db2f35c5eaf&action=add&service=${c}&link=${p}&quantity=${l}`:"Custom Comments"===r?v=`https://godofpanel.com/api/v2?key=7aed775ad8b88b50a1706db2f35c5eaf&action=add&service=${c}&link=${p}&comments=${s}`:"Comment Likes"===r?v=`https://godofpanel.com/api/v2?key=7aed775ad8b88b50a1706db2f35c5eaf&action=add&service=${c}&link=${p}&quantity=${l}&username=${a}`:"Poll"===r&&(v=`https://godofpanel.com/api/v2?key=7aed775ad8b88b50a1706db2f35c5eaf&action=add&service=${c}&link=${p}&quantity=${l}&answer_number=${s}`);let x=await fetch(v,{method:"GET"}),b=await x.json();if(!b.order)return i.NextResponse.json({success:!1,error:"Failed to fetch order from API"});let R=b.order,k=`
        INSERT INTO orders (category, service, quantity, link, charge, refill, panel, status, username, chat, uid, oid, name, father, answer_number, comments, usernames, rt, rtime)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 6528707984, $14, $15, $16, $17, $18)
        RETURNING id;
      `,y=[o,c,l,p,m,$,f,"Pending",u,`https://t.me/${u}`,n,R,g,t,s,a,`${h||null} days`,Date.now()],{rows:E}=await d.query(k,y),w=E[0].id,A=`
    UPDATE users
SET balance = CAST(balance AS NUMERIC) - CAST($1 AS NUMERIC)
WHERE id = (SELECT uid FROM orders WHERE id = $2)
RETURNING id, balance;
  `,{rows:S}=await d.query(A,[m,w]);if(!S[0])return i.NextResponse.json({success:"false"});return i.NextResponse.json({success:!0,orderId:w,orderOid:R,refill:$,url:v})}catch(e){return console.error("Error:",e),i.NextResponse.json({success:!1,error:e.message},{status:500})}}let c=new a.AppRouteRouteModule({definition:{kind:n.RouteKind.APP_ROUTE,page:"/api/smm/addOrder/route",pathname:"/api/smm/addOrder",filename:"route",bundlePath:"app/api/smm/addOrder/route"},resolvedPagePath:"D:\\next\\github\\telegram-starter-working\\app\\api\\smm\\addOrder\\route.tsx",nextConfigOutput:"",userland:s}),{workAsyncStorage:p,workUnitAsyncStorage:l,serverHooks:m}=c;function $(){return(0,o.patchFetch)({workAsyncStorage:p,workUnitAsyncStorage:l})}},8197:()=>{},1745:()=>{}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),s=r.X(0,[872,587],()=>t(9026));module.exports=s})();